### PR TITLE
Add Suspense to handle asynchronous component loading

### PR DESCRIPTION
**Pull request by tbl0605**
Hello @VojtechLanka,
Unfortunately I had to use my own version of vue-simple-suggest (based on your fork) for a few months, because it was missing support for asynchronous component loading (which I needed in the meantime).

For example, the following would not have worked without this patch, because the MyCustomAsyncLoadedInput component would not have been loaded in time for `this.$refs.inputSlot.querySelector('input')` to be non-null:
```vue
<vue-simple-suggest
  v-slot="{ componentField }"
  v-model="suggestion"
  :list="suggestions"
  value-attribute="key"
  display-attribute="label"
  :max-suggestions="100"
  :debounce="200"
  @update:modelSelect="setValuesFromSuggestion"
>
  <MyCustomAsyncLoadedInput
    v-model.trim="frenchPostalCode"
    v-bind="componentField"
    name="Postal code"
    pattern="^[0-9]{5}$"
    maxlength="5"
    autocomplete="off"
  />
</vue-simple-suggest>
```

The solution is to use the built-in [Suspense ](https://vuejs.org/guide/built-ins/suspense) component provided by Vue.js
It is marked as an experimental feature, but I haven't had any issues with it for months.
Strangely, I don't get the experimental feature warning (in development mode) anymore since Vue.js 3.5, maybe they forgot to update their website to mark it as stable.

Thierry.

### CODE REVIEW

**Comment by VojtechLanka** [comment]
Hi @tbl0605,
Thanks for the pull request. I cant promise anything but I will try to look at this by the end of this week.

**Comment by tbl0605** [comment]
Hi, 
No hurry, I wanted to share my changes so I can use your repo later again and delete mine ;)

Thank you,
Take care! :)

**Comment by VojtechLanka** [comment]
Looks fine. The only think I would like to be added is update to the README to mention that this feature is there (potentially with an example of how to use it). After that I will merge it and update the NPM package.

**Comment by tbl0605** [comment]
> Looks fine. The only think I would like to be added is update to the README to mention that this feature is there (potentially with an example of how to use it). After that I will merge it and update the NPM package.

Hi,
I hope my README update is good enough ;)
Feel free to correct it, English is not my native language ;)

**Comment by VojtechLanka** [comment]
Looks fine to me.

**Comment by VojtechLanka** [comment]
Published to [NPM](https://www.npmjs.com/package/@vojtechlanka/vue-simple-suggest) as version 2.1.0.

**Comment by tbl0605** [comment]
> Published to [NPM](https://www.npmjs.com/package/@vojtechlanka/vue-simple-suggest) as version 2.1.0.

Thank you!

**Pull request merged**
