### PR TITLE
Externalize component styles to allow better customization

### PR DESCRIPTION
**Pull request by tbl0605**
Hello @VojtechLanka,
this is my second (and last) issue with vue-simple-suggest.
In this patch, I simply externalized the component styles in a seperate file.
Most Vue.js libraries do this way, even the original vue-simple-suggest library has its `styles.css` file to import manually.
This way, the user can import the provided CSS file or write his own.

In my case, I really need my own custom CSS file for this library because my projects use some boostrap-based framework, providing its own theme.
I could easily overwrite some CSS rules defined by the vue-simple-suggest component, but I also needed to remove some other provided CSS rules because they were useless and conflicted with the boostrap-based framework.
In my case it was the CSS rules `.vue-simple-suggest.designed .input-wrapper input` and `.vue-simple-suggest.designed.focus .input-wrapper input` that needed to be deleted.
Since the  `dist/style.css` file is automatically imported by the vue-simple-suggest component I had no choice but to patch the `dist/style.css` file using the `patch-package` tool.

To test my patch, I also had to add the "prepare" script in the `package.json` file, otherwise the `dist` directory wasn't generated.
Maybe you won't have this problem on your side, if it's not necessary I'll remove this modification.

Thierry.

### CODE REVIEW

**Comment by VojtechLanka** [comment]
Hi @tbl0605,
I think that when I originally I have made the change to have the styles included always since in our project we always needed them (I think that was it, it was a while since I did that). But I do agree that having them imported explicitly by the user is much better idea.

I am not against separating the styles into the separate file but I am not sure it is needed here since they are rather small. The `import './style.css';` in the dist file is added by `vite-plugin-libcss`. If you remove the package and remove it from `vite.config.js` you should get the result you want. 

I will let the decision to separate the CSS into separate file or not on you but the `vite-plugin-libcss` should be removed either way as it should no longer be needed.

**Comment by VojtechLanka** [comment]
Also since we are technically restoring the original functionality of needing to import the styles separately I do not think it should be described in the `Breaking changes` part of README. I think only the first example should be updated to include something like in the original repo e.g. `@vojtechlanka/vue-simple-suggest/style.css' // Optional CSS`.

However I will have to publish it as version `3.0.0` since it is breaking change for this repo.

**Comment by tbl0605** [comment]
> I am not against separating the styles into the separate file but I am not sure it is needed here since they are rather small. The `import './style.css';` in the dist file is added by `vite-plugin-libcss`. If you remove the package and remove it from `vite.config.js` you should get the result you want.

Stupid me, I haven't seen the `vite-plugin-libcss` dependency :/
Btw, I still need the "prepare" script in the `package.json` file to generate the `dist`directory. Why wasn't this necessary before?

> I will let the decision to separate the CSS into separate file or not on you but the `vite-plugin-libcss` should be removed either way as it should no longer be needed.

Done ^^

> Also since we are technically restoring the original functionality of needing to import the styles separately I do not think it should be described in the `Breaking changes` part of README. I think only the first example should be updated to include something like in the original repo e.g. `@vojtechlanka/vue-simple-suggest/style.css' // Optional CSS`.

I added it in all the examples, so there will be no possible mistakes ^^

> However I will have to publish it as version `3.0.0` since it is breaking change for this repo.

Ok, that's a great idea.

**Comment by VojtechLanka** [comment]
> Btw, I still need the "prepare" script in the `package.json` file to generate the `dist`directory. Why wasn't this necessary before?
> 
> >
The `dist` is generated when `npm run build` is run. The `npm run dev` starts local web server with hot reload and the `npr run preview` start local web server but server the code from `dist`. So the `prepare` script should be removed and you should use the `npm run build` directly.

Two small changes:
1. I do not see the `import '@vojtechlanka/vue-simple-suggest/style.css'` in the very first example in the `Usage` section.
2. Additionally I realise now it was not there before but in the examples in the `Breaking changes` the line `import VueSimpleSuggest from '@vojtechlanka/vue-simple-suggest'` should be added as well for completeness because I think it is strage having the optional line there but not the one that is required.

**Comment by tbl0605** [comment]
Thank you for your clarifications, I have made the requested changes ^^

> The `dist` is generated when `npm run build` is run. The `npm run dev` starts local web server with hot reload and the `npr run preview` start local web server but server the code from `dist`. So the `prepare` script should be removed and you should use the `npm run build` directly.

My concern is rather to be sure that the `dist` directory will be present in the `node_modules/@vojtechlanka/vue-simple-suggest` directory immediately after doing `npm i @vojtechlanka/vue-simple-suggest`, strangely I could not make this work with my patch (but it works with the official 2.1.0 version) :/

**Comment by VojtechLanka** [comment]
The `dist` is made by me running the `npm run build` before `npm publish`. The code in the NPM is then static so the only reason why the `dist` would be missing is that I forgot to include it. I am not exactly sure what you were trying to do so I will not be much help here.

I have published the changes to [NPM](https://www.npmjs.com/package/@vojtechlanka/vue-simple-suggest) as version `3.0.0`.

**Comment by tbl0605** [comment]
> The `dist` is made by me running the `npm run build` before `npm publish`. The code in the NPM is then static so the only reason why the `dist` would be missing is that I forgot to include it. I am not exactly sure what you were trying to do so I will not be much help here.

Ok now I understand better how the `dist` directory was built.

> I have published the changes to [NPM](https://www.npmjs.com/package/@vojtechlanka/vue-simple-suggest) as version `3.0.0`.

Thank you very much!
Take care! ^^

**Pull request merged**
